# Class: deploystudio
# This module sets up DeployStudio for both
# Masters and Replicas
#
# osx_server_account_hash is used to create a service account on OS X 
#
# ds_service_account_hash is generated by DeployStudio. You must setup DS once
# manually with the desired password to get this hash. (This is stored in 
# /Library/Preferences/com.deploystudio.server.plist)

class osx_deploystudio(
  $ds_role='replica',
  $ds_master_url='https://deploystudiomaster.domain.com:60443',
  $service_account_name='deploystudio',
  $osx_service_account_hash='OSXShadowHashGoesHere',
  $ds_service_account_hash='DeployStudioHashGoesHere',
  $ds_repo_url='afp://servername/sharename',
  $ds_admin_group='dsadmin',
  $ds_assistant_group='dsassistant',
  $ds_runtime_group='dsruntime',
) {
  if $::operatingsystem != 'Darwin' {
    fail('DeployStudio only runs on OS X')
  }

  class{'osx_deploystudio::install': } ->
  class{'osx_deploystudio::user': } ->
  class{'osx_deploystudio::config': } ~>
  class{'osx_deploystudio::service': } ->
  Class['osx_deploystudio']
}
